# encoding: utf-8
import random

NSQD_HTTP_ADDRESS = '127.0.0.1:4151'
NSQD_TCP_ADDRESSES = ['127.0.0.1:4150', ]

# CONTENT以外にも使えるように前後100ずつ空けとく
AVAILABLE_PORT_BASE = 49152 + 100
AVAILABLE_CONTENT_PORT_MAX = 65535 - 100

TOPIC_REGISTER_CLIENT = 'p2ptest1_register_client'

PEER_CONTENT_ROOT = ''

MAX_PEER_COUNT = 100

PEER_PING_TIMEOUT = 5

QUERY_REGISTER_CLIENT = 'register'
QUERY_IS_CLIENT_ALIVE = 'ping'

QUERY_SUCCESS = 'ok'
QUERY_ERROR = 'ng'


def get_random_port():
    return random.randint(AVAILABLE_PORT_BASE, AVAILABLE_CONTENT_PORT_MAX)
